import type { Metadata } from "next";
import { Montserrat } from "next/font/google";// استبدال الخطوط بـ Roboto و Roboto_Mono
import "./globals.css";

// استيراد خطوط جديدة وتعيين المتغيرات
const montserrat = Montserrat({
  weight: ["400", "600", "700"], // الأوزان التي ترغب باستخدامها
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "my-project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
